### ISSUE TITLE
Routing not working as expected

### ISSUE THREAD

**Issue by TimThaens** [Araffe/vdc-networking-lab#3]
Hi Araffe,
Great networking lab!
However, the routing you've set up is not working as intended.
With enabling the "Use remote gateways" and "Allow gateway transit" options on the peering, the entire routing goes via the "Default" and "Virtual network gateway" routes, and not via the User routes.
You can just shutdown the NVA, delete all the UDR's, and the routing from the OnPrem to the Spoke VM's will continue to work.

**Comment by TimThaens** [comment]
Sorry my bad, those gateway routes are invalidated by the UDR's

**Comment by Araffe** [comment]
No worries, glad you're enjoying the lab!
